language: cpp

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          compiler: gcc
        - os: osx
          osx_image: xcode7.3
          compiler: gcc
        - os: osx
          osx_image: xcode7.3
          compiler: clang

before_install:
    - |
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            brew update
            brew install premake
        fi
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            sudo apt-get -qq update -y
            sudo apt-get install premake4 -y
        fi

before_script:
    - git clone https://github.com/neuromorphic-paris/sepia.git
    - cd sepia && premake4 install && cd ..
    - git clone https://github.com/neuromorphic-paris/tarsier.git
    - cd tarsier && premake4 install && cd ..

script:
    - premake4 gmake
    - cd build
    - make
